name: food_master
description: Food recipe app

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  # Classes and helper functions that support JSON code generation via the 'json_serializable' package.
  json_annotation: ^2.0.0

  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  json_serializable: ^2.0.0

  # A composable, cross-platform, Future-based API for making HTTP requests.
  http: ^0.12.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Tools to write binaries that run builders.
  build_runner: ^1.1.2

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
